name: Automate Commit and Pull Request

on:
  push:
    branches:
      - main

jobs:
  auto-commit-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Make changes
      run: |
        # Ajoutez ici vos commandes pour modifier les fichiers
        echo "Modification automatique par GitHub Actions" >> modifications.txt

    - name: Commit changes
      run: |
        git add .
        git commit -m "Commit automatique : Mise à jour par workflow"

    - name: Push changes
      run: git push origin main

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Pull Request Automatique"
        body: "Cette pull request a été créée automatiquement par GitHub Actions."
        branch: auto-changes